server.port=8080

# Configuración para conectar con tu base de datos en Supabase
spring.datasource.url=jdbc:postgresql://db.mfdvphvbhftpvkvlrejo.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=uyDSptQePOlA7VED
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Upload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# Security
jwt.secret=GemaInventoryProfessionalSecurityKey2026FixedSecretForDevelopment

# Error reporting
server.error.include-message=always

# Resend Email Configuration
resend.api.key=re_9eMrZAns_6sWzaq87V8V5J2NaF21edJDM
